import {
  AlarmClock,
  Apple,
  Award,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Check,
  CircleDot,
  Code,
  Droplets,
  Dumbbell,
  Flag,
  Flame,
  Footprints,
  Gamepad2,
  Gem,
  GraduationCap,
  Heart,
  Leaf,
  Medal,
  Moon,
  Mountain,
  Music,
  PenTool,
  PiggyBank,
  Plane,
  Rocket,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Target,
  Trophy,
  Wallet,
  type LucideIcon
} from 'lucide-react'

/** 可挑选的图标名（新增习惯/目标时存入数据库的值） */
export const ICON_CHOICES = [
  'droplets',
  'book-open',
  'dumbbell',
  'mountain',
  'moon',
  'alarm-clock',
  'flame',
  'heart',
  'apple',
  'footprints',
  'sun',
  'leaf',
  'brain',
  'sparkles',
  'music',
  'brush',
  'code',
  'gamepad-2',
  'smile',
  'star',
  'check',
  'target',
  'trophy',
  'medal',
  'award',
  'piggy-bank',
  'wallet',
  'rocket',
  'graduation-cap',
  'briefcase',
  'plane',
  'sprout',
  'flag',
  'gem',
  'bike',
  'pen-tool'
] as const

export type IconName = (typeof ICON_CHOICES)[number]

const ICON_MAP: Record<string, LucideIcon> = {
  droplets: Droplets,
  'book-open': BookOpen,
  dumbbell: Dumbbell,
  mountain: Mountain,
  moon: Moon,
  'alarm-clock': AlarmClock,
  flame: Flame,
  heart: Heart,
  apple: Apple,
  footprints: Footprints,
  sun: Sun,
  leaf: Leaf,
  brain: Brain,
  sparkles: Sparkles,
  music: Music,
  brush: Brush,
  code: Code,
  'gamepad-2': Gamepad2,
  smile: Smile,
  star: Star,
  check: Check,
  target: Target,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  rocket: Rocket,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  plane: Plane,
  sprout: Sprout,
  flag: Flag,
  gem: Gem,
  bike: Bike,
  'pen-tool': PenTool,
  // 旧数据遗留的 emoji → 图标映射，保证存量数据不再渲染 emoji
  '✅': Check,
  '🎯': Target,
  '😀': Smile,
  '🔥': Flame,
  '💧': Droplets,
  '📚': BookOpen,
  '🏃': Footprints,
  '💪': Dumbbell,
  '⏰': AlarmClock,
  '💤': Moon,
  '❤️': Heart,
  '⭐': Star,
  '🏆': Trophy,
  '🎮': Gamepad2,
  '🎵': Music,
  '✍️': PenTool,
  '💼': Briefcase,
  '✈️': Plane,
  '🌱': Sprout,
  '🚩': Flag,
  '💎': Gem,
  '🚴': Bike,
  '🎓': GraduationCap,
  '🚀': Rocket,
  '🎨': Brush,
  '🎧': Music,
  '📖': BookOpen,
  '🏋️': Dumbbell,
  '🧘': Sparkles,
  '🥗': Apple,
  '🍎': Apple,
  '💊': Heart,
  '💰': Wallet,
  '💵': Wallet,
  '📈': Target,
  '🏠': Briefcase,
  '🌙': Moon,
  '☀️': Sun,
  '🌿': Leaf
}

const FALLBACK_ICON: LucideIcon = CircleDot

/** 把存储值（图标名或历史 emoji）解析成 lucide 图标组件；无法识别时回退默认图标 */
export function resolveIcon(value?: string | null): LucideIcon {
  if (value) {
    const icon = ICON_MAP[value]
    if (icon) return icon
  }
  return FALLBACK_ICON
}
